const ASSET='https://dzlmtvodpyhetvektfuo.supabase.co/storage/v1/object/public/brand-graphics/';
const companies={
'fraternity':{name:'The Fraternity',eyebrow:'Culture · Entertainment · Global Influence',cover:`${ASSET}dr_dorsey/website/penthouse-skyline.jpg`,about:'A selective, multicultural organization of DJs, cultural architects, entertainment leaders, and global power players. The Fraternity is designed as a command center for culture, economic empowerment, elevated learning, global reach, and legacy building.',actions:[['Enterprise Inquiry','https://thekollectivehospitality.com/forms/inquiry?brand=the-fraternity'],['Request NDA','/nda.html']]},
'casper-group':{name:'The Casper Group',eyebrow:'Quick-Service Food Portfolio',cover:`${ASSET}casper_group/logos/logo-full.png`,about:'A portfolio of independent food brands designed for delivery, food halls, licensing, packaged expansion, and multi-location growth. Concepts include Angel Wings, Espresso Co., Mojo Juice Bar, Tha Morning After, Mr. Oyster, Pasta Bish, Patty Daddy, Sweet Tooth, Taco Yaki, Toss’d, Peace Pizza, and American Dragon.',actions:[['Food & Licensing Inquiry','https://thekollectivehospitality.com/forms/group_pricing'],['Enterprise Inquiry','https://thekollectivehospitality.com/forms/inquiry?brand=casper-group']]},
'umbrella-group':{name:'The Umbrella Group',eyebrow:'Services · One Request, Correct Routing',cover:`${ASSET}good-times-app/umbrella_group/umbrella_group_landscape.png`,about:'A unified services network spanning auto exchange, realty, injury support, The Mind Studio, clean services, brand services, automation, people services, and accounting. One intake routes each request to the right operating lane.',actions:[['Start a Service Request','https://thekollectivehospitality.com/forms/inquiry?brand=umbrella-group'],['View All Access','https://thekollectivehospitality.com/access']]},
'rose-on-piedmont':{name:'Rose on Piedmont',eyebrow:'Atlanta Hospitality · Weekly Programming',cover:`${ASSET}social-dashboard/2026-07-17/dolodorsey/rose-bar-free-hookah.png`,about:'A hospitality and nightlife destination for weekly programming, private celebrations, patio energy, tables, birthdays, art, and current Atlanta experiences.',actions:[['See Current Schedule','/#events'],['Reserve / Birthday','/#actions']]},
'grown-ish':{name:'GROWN-ISH',eyebrow:'Friday Nightlife · Rose on Piedmont',cover:`${ASSET}grownish/03_event_flyers/GROWNISH_COMING_SOON.png`,about:'A Friday nightlife experience built around grown energy, birthdays, premium tables, music, and direct access through 111ATL.',actions:[['Current Schedule','/#events'],['Reserve Friday','/#actions']]},
'sole-exchange':{name:'Sole Exchange',eyebrow:'Community · Sneaker Impact',cover:`${ASSET}email-newsletters/sole-exchange-flyer-v3-air-force-1.png`,about:'A community platform centered on sneaker culture, collection drives, giving, youth access, cultural activations, and measurable local impact.',actions:[['Support / Volunteer','https://thekollectivehospitality.com/forms/volunteer?brand=sole-exchange'],['Partnership Inquiry','https://thekollectivehospitality.com/forms/sponsor?brand=sole-exchange']]},
'taste-of-art':{name:'Taste of Art',eyebrow:'Art · Food · Music · Cultural Experience',cover:`${ASSET}taste_of_art/03_event_flyers/TASTE_ROSE_BAR_0717_v4.png`,about:'An art-forward cultural experience merging visual art, hospitality, music, live programming, creative commerce, and community discovery.',actions:[['Current Programming','/#events'],['Artist / Partner Inquiry','https://thekollectivehospitality.com/forms/artist_painter?brand=taste-of-art']]},
'pulse':{name:'PULSE',eyebrow:'Athletic · Golf · Lounge · Lifestyle',cover:`${ASSET}pulse/pulse_landing_v1/021_pulse_3d_logo_stage.jpg`,about:'An athletic and lifestyle brand designed around motion, signal, social energy, golf, elevated basics, and everyday uniforms.',actions:[['Product Inquiry','https://thekollectivehospitality.com/forms/inquiry?brand=pulse'],['Wholesale / Partnership','https://thekollectivehospitality.com/forms/sponsor?brand=pulse']]},
'mind-studio':{name:'The Mind Studio',eyebrow:'Virtual + In-Home Wellness Access',cover:`${ASSET}mind_studio/gt_card_mind_studio.png`,about:'A national mental wellness access platform designed for discreet intake, virtual-first support, in-home options where available, consistent scheduling, and partner referral channels.',actions:[['Request Support','https://thekollectivehospitality.com/forms/inquiry?brand=mind-studio'],['Partner With The Mind Studio','https://thekollectivehospitality.com/forms/sponsor?brand=mind-studio']]},
'scented-flowers':{name:'Scented Flowers',eyebrow:'Museum Series · Culture Preserved',cover:`${ASSET}dr_dorsey/website/garden-district.jpg`,about:'A museum and immersive-experience series built to preserve moments, legends, sports, music, culture, and stories through modern public experiences.',actions:[['Museum / Venue Inquiry','https://thekollectivehospitality.com/forms/inquiry?brand=scented-flowers'],['Sponsor an Experience','https://thekollectivehospitality.com/forms/sponsor?brand=scented-flowers']]}
};
const key=new URLSearchParams(location.search).get('brand');const c=companies[key]||companies['casper-group'];document.title=`${c.name} | 111ATL`;document.querySelector('#companyPage').innerHTML=`<section class="company-detail"><div class="company-cover"><img src="${c.cover}" alt="${c.name}"></div><div class="company-copy"><p class="section-kicker">${c.eyebrow}</p><h1>${c.name}</h1><p>${c.about}</p><div class="intro-actions">${c.actions.map((a,i)=>`<a class="button ${i?'outline':'gold'}" href="${a[1]}">${a[0]}</a>`).join('')}</div></div></section>`;
