const ASSET='https://dzlmtvodpyhetvektfuo.supabase.co/storage/v1/object/public/brand-graphics/';
const state={events:[],eventFilter:'all',entityFilter:'all',entityQuery:''};
const entities=[
{key:'dr-dorsey',name:'Dr. Dorsey',category:'enterprise',description:'Founder, lifestyle specialist, author, strategist, and cultural operator.',logo:`${ASSET}dr_dorsey/01_logos/DORSEY_LOGO.png`,cover:`${ASSET}dr_dorsey/website/penthouse-skyline.jpg`,url:'https://doctordorsey.com'},
{key:'kollective',name:'The Kollective ENT.',category:'enterprise',description:'The enterprise command layer connecting independent brands, systems, partnerships, and expansion.',logo:`${ASSET}dr_dorsey/00-brand-assets/logos/kollective-emblem-gold-white.png`,cover:`${ASSET}dr_dorsey/website/luxury-venue.jpg`,url:'https://thekollectivehospitality.com'},
{key:'fraternity',name:'The Fraternity',category:'culture',description:'A multicultural organization of DJs, cultural architects, and global power players.',cover:`${ASSET}dr_dorsey/website/penthouse-skyline.jpg`,url:'/company.html?brand=fraternity'},
{key:'casper-group',name:'The Casper Group',category:'enterprise',description:'A scalable portfolio of distinct quick-service food brands and licensing concepts.',logo:`${ASSET}casper_group/logos/casper-group.png`,cover:`${ASSET}casper_group/logos/logo-full.png`,fit:'contain',url:'/company.html?brand=casper-group'},
{key:'umbrella-group',name:'The Umbrella Group',category:'services',description:'One service network for auto, realty, injury, wellness, cleaning, branding, automation, people, and accounting.',cover:`${ASSET}good-times-app/umbrella_group/umbrella_group_landscape.png`,fit:'contain',url:'/company.html?brand=umbrella-group'},
{key:'university',name:'The University',category:'enterprise',description:'A practical trade, workforce, credentialing, and ownership platform.',cover:`${ASSET}pulse_university/website/WEBSITE_HERO_DRIVE_EVERY_MOMENT.png`,url:'https://the-university.vercel.app'},
{key:'rose',name:'Rose on Piedmont',category:'experience',description:'Atlanta hospitality, patio culture, private events, and current weekly programming.',cover:`${ASSET}social-dashboard/2026-07-17/dolodorsey/rose-bar-free-bottle.png`,fit:'contain',url:'/company.html?brand=rose-on-piedmont'},
{key:'grownish',name:'GROWN-ISH',category:'experience',description:'Friday nightlife at Rose on Piedmont with birthdays, tables, music, and grown energy.',cover:`${ASSET}grownish/03_event_flyers/GROWNISH_COMING_SOON.png`,fit:'contain',url:'/company.html?brand=grown-ish'},
{key:'good-times',name:'GOOD TIMES',category:'experience',description:'Curated lifestyle technology, city discovery, events, restaurants, and concierge access.',logo:`${ASSET}good_times/00-brand-assets/logos/good-times-logo-gold-black.png`,cover:`${ASSET}good_times/atl-nightlife-elevated.png`,url:'https://thegoodtimesworldwide.com'},
{key:'sole-exchange',name:'Sole Exchange',category:'culture',description:'Community sneaker impact, cultural activations, collection drives, and access.',logo:`${ASSET}email-newsletters/sole-exchange-logo.png`,cover:`${ASSET}email-newsletters/sole-exchange-flyer-v3-air-force-1.png`,fit:'contain',url:'/company.html?brand=sole-exchange'},
{key:'taste-of-art',name:'Taste of Art',category:'experience',description:'Art, culture, music, and hospitality presented through live public experiences.',cover:`${ASSET}taste_of_art/03_event_flyers/TASTE_ROSE_BAR_0717_v4.png`,fit:'contain',url:'/company.html?brand=taste-of-art'},
{key:'hakuna-matata',name:'Hakuna Matata',category:'products',description:'Dr. Dorsey’s book and founder philosophy on enjoying life while building legacy.',cover:`${ASSET}bodega/hakuna-matata/promo-05-gold-columns.png`,url:'https://bodgeaworldwide.myshopify.com/products/hakuna-matata-by-dr-dorsey'},
{key:'bodega',name:'Bodega',category:'products',description:'A culture-forward commerce platform for creative products, books, and lifestyle goods.',cover:`${ASSET}bodega/hakuna-matata/promo-02-graffiti-red.png`,url:'https://bodegabodegabodega.com'},
{key:'stush',name:'STUSH',category:'products',description:'Premium fashion, elevated streetwear, limited drops, and statement pieces.',cover:`${ASSET}stush/stush_lineup/063_the_stush_lineup.jpg`,url:'https://stushusa.com'},
{key:'pulse',name:'PULSE',category:'products',description:'Athletic, golf, lounge, and lifestyle apparel built around movement and signal.',cover:`${ASSET}pulse/pulse_landing_v1/021_pulse_3d_logo_stage.jpg`,url:'/company.html?brand=pulse'},
{key:'maga',name:'Make Atlanta Great Again',category:'products',description:'Atlanta culture, apparel, nostalgia, civic pride, and real city energy.',cover:`${ASSET}maga/generated/maga_hero.png`,url:'https://thaoldatlanta.com'},
{key:'pronto',name:'Pronto Energy',category:'products',description:'Consumer energy beverage built for fitness, nightlife, sports, festivals, and everyday momentum.',logo:`${ASSET}pronto_energy/logos/pronto-logo.png`,cover:`${ASSET}pronto_energy/generated/pronto_gym_hero_v2.png`,url:'https://pronto-energy-website.vercel.app'},
{key:'help-911',name:'Help 911',category:'services',description:'The call after the call: accident support, routing, documentation, and next-step coordination.',logo:`${ASSET}umbrella_injury/00-brand-assets/logos/hurt-911-logo-black.png`,cover:`${ASSET}help911/the_call_after_the_call/042_accident__911_first__help911_next.jpg`,url:'https://superherosonstandby.com'},
{key:'mind-studio',name:'The Mind Studio',category:'services',description:'Virtual and in-home mental wellness access with discreet, consistent support.',cover:`${ASSET}mind_studio/gt_card_mind_studio.png`,fit:'contain',url:'/company.html?brand=mind-studio'},
{key:'scented-flowers',name:'Scented Flowers',category:'culture',description:'Museum-series experiences preserving sports, legends, culture, and meaningful stories.',logo:`${ASSET}dr_dorsey/00-brand-assets/logos/iconic-logo-gold.png`,cover:`${ASSET}dr_dorsey/website/garden-district.jpg`,url:'/company.html?brand=scented-flowers'}
];
const $=(q,s=document)=>s.querySelector(q); const $$=(q,s=document)=>[...s.querySelectorAll(q)];
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function dateLabel(v){if(!v)return'Date TBA';return new Date(`${v}T12:00:00`).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}
function days(v){const t=new Date();t.setHours(0,0,0,0);return Math.round((new Date(`${v}T00:00:00`)-t)/86400000)}
function eventMatch(e){const d=days(e.event_date);if(state.eventFilter==='tonight')return d===0;if(state.eventFilter==='week')return d>=0&&d<=7;return true}
function eventCard(e){const flyer=e.metadata?.flyer_approved===true&&e.flyer_url?`<img src="${esc(e.flyer_url)}" alt="${esc(e.title)} flyer">`:`<div class="generated-poster"><small>${esc(dateLabel(e.event_date))}</small><strong>${esc(e.title||'Current Program')}</strong><span>${esc(e.venue||'Atlanta')}</span></div>`;return `<article class="event-card"><div class="event-poster">${flyer}</div><div class="event-body"><small>${esc(dateLabel(e.event_date))}</small><h3>${esc(e.title||'Current Program')}</h3><p>${esc(e.subtitle||e.metadata?.theme||'Current access through 111ATL.')}</p><a href="#actions">RSVP / RESERVE →</a></div></article>`}
function renderEvents(){const list=state.events.filter(eventMatch);$('#eventGrid').innerHTML=list.length?list.map(eventCard).join(''):`<article class="event-card"><div class="event-poster"><div class="generated-poster"><small>Schedule update</small><strong>New programming loading</strong></div></div><div class="event-body"><h3>Stay connected</h3><p>The current calendar is being updated.</p><a href="#actions">JOIN THE LIST →</a></div></article>`;$('#eventsStatus').textContent=`${list.length} current program${list.length===1?'':'s'}`}
async function loadEvents(){try{const r=await fetch('/api/events',{headers:{Accept:'application/json'}});const j=await r.json();state.events=Array.isArray(j.events)?j.events:Array.isArray(j)?j:[];renderEvents()}catch(e){console.error(e);state.events=[];renderEvents()}}
function entityCard(e){return `<a class="entity-card" href="${esc(e.url)}" ${e.url.startsWith('http')?'target="_blank" rel="noopener"':''}><div class="entity-media ${e.fit==='contain'?'contain':''}"><img class="cover" src="${esc(e.cover)}" alt="${esc(e.name)} visual" loading="lazy">${e.logo?`<img class="logo" src="${esc(e.logo)}" alt="${esc(e.name)} logo" loading="lazy">`:''}</div><div class="entity-info"><small>${esc(e.category)}</small><h3>${esc(e.name)}</h3><b>↗</b><p>${esc(e.description)}</p></div></a>`}
function renderEntities(){const q=state.entityQuery.toLowerCase().trim();const list=entities.filter(e=>(state.entityFilter==='all'||e.category===state.entityFilter)&&(!q||`${e.name} ${e.description} ${e.category}`.toLowerCase().includes(q)));$('#entityGrid').innerHTML=list.map(entityCard).join('');$('#entityStatus').textContent=`${list.length} current companies shown.`}
$$('[data-event-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-event-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.eventFilter=b.dataset.eventFilter;renderEvents()}));
$$('[data-entity-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-entity-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.entityFilter=b.dataset.entityFilter;renderEntities()}));
$('#entitySearch').addEventListener('input',e=>{state.entityQuery=e.target.value;renderEntities()});
window.addEventListener('scroll',()=>$('#siteHeader').classList.toggle('scrolled',scrollY>20),{passive:true});
renderEntities();loadEvents();
